name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: itdoesnotrun
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container on Nix
        run: nix build .#docker

      - name: Load result container
        run: docker load < result

      - name: Setup flyctl
        uses: https://github.com/superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
